version: "3.9"

services:
  backend:
    build: .
    container_name: backend
    ports:
      - "8000:8000"
    environment:
      - AI_URL=http://ai:8001/predict
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    depends_on:
      - ai
    networks:
      - app-network

  ai:
    build: ../ai
    container_name: ai
    ports:
      - "8001:8001"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    networks:
      - app-network

  frontend:
    build: ../frontend
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge